apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nats-allow-from-current-ns
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Release.Namespace }}
  podSelector:
    matchLabels:
      component: nats
  policyTypes:
  - Ingress
